<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ST Testing Service</title>
    <meta name="description" content="THE DESIGN OF THE INSULATION SYSTEM FOR METAL-ENCLOSED SWITCHGEAR IS BASED UPON LIFE EXPECTANCY OF ABOUT 30 YEARS. INDIVIDUAL TESTS OR ROUTINE VERIFICATIONS ARE INTENDED TO CHECK THE ESSENTIAL SAFETY ASPECTS OF HV/LV ASSEMBLIES THAT COULD BE AFFECTED BY HAZARDS DURING MOUNTING OR POSSIBLE MANUFACTURING FAULTS. IN PRINCIPLE, THEY MUST BE CARRIED OUT ON ALL ASSEMBLIES, EITHER IN THE WORKSHOP OR AT THE INSTALLATION SITE. HIGH-VOLTAGE TRANSFORMERS ARE SOME OF THE MOST IMPORTANT (AND EXPENSIVE) PIECES OF EQUIPMENT REQUIRED FOR OPERATING A POWER SYSTEM. WHEN TRANSFORMERS ARE RECEIVED FROM ANOTHER LOCATION IT IS NECESSARY TO VERIFY THAT EACH TRANSFORMER IS DRY, NO DAMAGE HAS OCCURRED DURING SHIPPING, INTERNAL CONNECTIONS HAVE NOT BEEN LOOSENED, THE TRANSFORMER’S RATIO, POLARITY AND IMPEDANCE AGREE WITH ITS NAMEPLATE, ITS MAJOR INSULATION STRUCTURE IS INTACT, WIRING INSULATION HAS NOT BEEN BRIDGED, AND THEN THE TRANSFORMER IS READY FOR SERVICE. CABLING IS AN EXPENSIVE BUSINESS AND MUST BE TREATED CAREFULLY. THE EXPENDITURE OF SUBSTITUTION ONCE THE ROUTES ARE ALL CONCEALED IS BIGGER. THE FAULT IS NOT ALWAYS VISIBLE LIKE CRUSHING, BENDING OR KINKING. MAKE SURE THAT YOUR CABLING INSTALLER HAVE MADE PROVISION TO PROTECT INSTALLED CABLING FROM OTHER WORKER’S ACTIONS. THIS IS SUBSTANTIALLY LESS COSTLY THAN CHANGING CABLING IN THE FUTURE. IF CABLE ROUTES ARE GUARDED WITH NO WAY OF OPENING THEM BETWEEN TERMINATION AND INSTALLATION, IT IS IDEAL TO TERMINATE THE CABLES FOR THE TIME BEING, SO THEY CAN BE TESTED BEFORE THE ROUTES ARE PROTECTED. ELECTRICAL PANELS AND ENCLOSURES ARE FOUND IN EVERY INDUSTRY ACROSS THE WORLD. COST-EFFECTIVE SYSTEM TO ELIMINATE FIRES AT THE SOURCE. WE PROTECT ALL SIZES OF PANELS, FROM SMALL ELECTRICAL BOXES TO ROOMS FILLED WITH ELECTRICAL ENCLOSURES. ELECTRICAL PANELS AND ENCLOSURES ARE FOUND IN EVERY INDUSTRY ACROSS THE WORLD. COST-EFFECTIVE SYSTEM TO ELIMINATE FIRES AT THE SOURCE. WE PROTECT ALL SIZES OF PANELS, FROM SMALL ELECTRICAL BOXES TO ROOMS FILLED WITH ELECTRICAL ENCLOSURES.">
    <meta name="keywords" content="SWITCHGEARS, TRANSFORMERS, CABLES, ELECTRICAL FIRE SUPPRESSION SYSTEM, ADVANCE TECHNOLOGY, WORLD QUALITY SERVICE, INTELLIGENT SOLUTIONS, LIFETIME SUPPORT">
    <link rel="icon" href="img/favicon.png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- animate CSS -->
    <link rel="stylesheet" href="css/animate.css">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <!-- themify CSS -->
    <link rel="stylesheet" href="css/themify-icons.css">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="css/flaticon.css">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="css/magnific-popup.css">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="css/slick.css">
    <!-- style CSS -->
    <link rel="stylesheet" href="css/style.css">
    <link href="css/common.css" rel="stylesheet" type="text/css"/>
    <link href="css/sweetalert.css" rel="stylesheet" type="text/css"/>
</head>