<head>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-52115242-17"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-52115242-17');
    </script>
    <meta charset="utf-8">
    <title>Project Next Door</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Bootstrap HTML template and UI kit by Medium Rare">
    <!-- Begin loading animation -->
    <style>
        @keyframes hideLoader{ 0%{ width: 100%; height: 100%; } 100%{ width: 0; height: 0; } } body > div.loader{ position: fixed; background: white; width: 100%; height: 100%; z-index: 1071; opacity: 0; transition: opacity .5s ease; overflow: hidden; pointer-events: none; display: flex; align-items: center; justify-content: center; } body:not(.loaded) > div.loader{ opacity: 1; } body:not(.loaded){ overflow: hidden; } body.loaded > div.loader{ animation: hideLoader .5s linear .5s forwards; } .loading-animation{width:40px;height:40px;margin:100px auto;background-color:#2568ef;border-radius:100%;animation:pulse 1s infinite ease-in-out}@keyframes pulse{0%{-webkit-transform:scale(0);transform:scale(0)}100%{-webkit-transform:scale(1);transform:scale(1);opacity:0}}
    </style>
    <script type="text/javascript">
        window.addEventListener("load", function () {
            document.querySelector('body').classList.add('loaded');
        });
    </script>

    <!-- End loading animation -->
    <link href="assets/css/theme.min.css" rel="stylesheet" type="text/css" media="all" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <!--    <link href="https://fonts.googleapis.com/css?family=Nunito:400,400i,600,700&amp;display=swap" rel="stylesheet">-->
    <link href="css/style.css" rel="stylesheet" type="text/css"/>
    <link href="css/all.min.css" rel="stylesheet" type="text/css"/>
    <link href="css/fontawesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="css/responsive.css" rel="stylesheet" type="text/css"/>
    <style>
        /* #### Generated By: http://www.cufonfonts.com #### */

        @font-face {
            font-family: 'Antonio Regular';
            font-style: normal;
            font-weight: normal;
            src: local('Antonio Regular'), url('fonts/antonio/Antonio-Regular.woff') format('woff');
        }


        @font-face {
            font-family: 'Antonio Light';
            font-style: normal;
            font-weight: normal;
            src: local('Antonio Light'), url('fonts/antonio/Antonio-Light.woff') format('woff');
        }


        @font-face {
            font-family: 'Antonio Bold';
            font-style: normal;
            font-weight: normal;
            src: local('Antonio Bold'), url('fonts/antonio/Antonio-Bold.woff') format('woff');
        }

        @font-face {
            font-family: 'Smithen Regular';
            font-style: normal;
            font-weight: normal;
            src: local('Smithen Regular'), url('fonts/antonio/Smithen Script.woff') format('woff');
        }
    </style>
</head>